export const GET_FOOD_CATEGORY_REQUEST = "GET_FOOD_CATEGORY_REQUEST";

export const GET_FOOD_CATEGORY_SUCCESS = "GET_FOOD_CATEGORY_SUCCESS";

export const GET_FOOD_CATEGORY_FAILURE = "GET_FOOD_CATEGORY_FAILURE";



export const GET_FOOD_TYPE_REQUEST = "GET_FOOD_TYPE_REQUEST";

export const GET_FOOD_TYPE_SUCCESS = "GET_FOOD_TYPE_SUCCESS";

export const GET_FOOD_TYPE_FAILURE = "GET_FOOD_TYPE_FAILURE";